<h2 style = 'color:purple;'>Unit vector:</h2> <br>


### Unit vector is a vector with a magnitude of 1.Dimensions of Unit vector is calculated from a given set of vectors such that the maghnitude of unit vector is 1.


<h2 style = 'color:red;'>Now we need to find a unit vector for a given graph,such that when we project every point in a graph to the unit vector,then it results into maximum variance.</h2>

<img src = 'unit_vector.png'/>

### In above,reds are the points of vector from input features,U is the unit vector,and all the points are projected to unit vector.Unit vector must be choosen such that it offers maximum variance.Maximum variance means maximum features.

### Now each vectors ${(x_1,x_2,x_3.....x_n)}$ can be projected (means prurple line) with new representation as ${(U^{T}x_1,U^{T}x_2,U^{T}x_3.....U^{T}x_n)}$

### So thus variance(before projection to unit vector) was $1/n{\sum_{i=0}^{n} (X_i - \bar{X})^{2}}$ which then becomes $1/n\sum_{i=0}^{n} (U^{T}X_i - \bar{X}U^{T})^{2}$ where ${U^{T}}$ is the projection factor



### Now i have to find ${U^{T}}$ such that it have maximum variance

<img src = "cov.png">

### Covariance and correlation are similar concept.Covariance can be anything but correlation is within the range of 1 and -1

<h2 style = 'color:purple;'>Covariance matrix:</h2>

<img src = 'confusion_matrix.png'/>

<img src = 'cv.png'/>

<h2 style = 'color:purple'>Eigen vector and Eigen Value</h2>

### In a simple word matrix is a linear transformation value which transforms the original coordinate system such that when we plot the point in a new transformed coordinate system,then the both magnitude and direction of the point may changed.So for any given point,whose direction is same in a transformed coordinate system too but the maghnitude differs,it is called eigen vector.And a value of stretch from old vector to new one is called eigen value

<img src = 'eigen 1.png'/>
<img src = 'eigen 2.png'/>

<h2 style = 'color:purple;'>Why eigen value and vector are needed in PCA?</h2>

### When we calculate the eigen value and vector for a covariance matrix,then the largest eigen vector i.e. largest eigen value will be pointing toward large variance which means that we have to choose the eigen vector as unit vector which have largest eigen value(largest eigen value means vectors on which largest variance can be found).These vector is used to project all the points in the coordinate system.

<h2 style = 'color:purple;'>How PCA works in steps</h2>

### let us consider a input with three features and a label output

### 1) Calculating the mean center : Mean center takes all the data to the origin making the resulting mean 0 (Same as standarization) as :

<img src="m.png"/>

### 2) Find a convariance matrix for 3D features

<img src = 'c.png'/>

### where f1,f2,f3 are input features

### 3) Find the eigen value for features and choose the largest eigen valued vector.

### Largest eigen value become PC1,second one become PC2 and third one become PC3.Now we can represent our data in form of only 1D by taking PC1 or in 2D by raking PC1 and PC2

<h2 style = 'color:purple;'>How to transform point in higher dimension into lower one</h2>

### Let us consider above dataset with 1000 rows and three feature(1000,3) and one label.Now for converting 3D points into 1D points,we have to take 1 PC i.e. PC1 where all the input points are projected. in figure below PC1 is a vector in 3D space so its coordinates is (1,3) i.e. 1 vector in 3D space, on which all the points are to be projectted.We will be projecting all the points in PC1 by finding dot product as (1000,3).(1,3).After transpose in (1,3),it becomes (3,1).So (1000,3).(3,1) = (1000,1).Here it is 1D

<img src= 'J.png'/>

### For converting 3D points to 2D points,we have a data with (1000,3) and two PC in 3D dimension i.e. (2,3).After performing transpose on (2,3) it becomes (3,2).So we will be projecting all this point into these two PC's by finding dot product as (1000,3).(3,2) which becomes (1000,2)

# CODE DEMO (dataframe contains binary numbers i.e. 0 and 1)

In [142]:
import pandas as pd
import numpy as np

np.random.seed(43) ##This code is used to generate the same output randomly everytime the code runs.We can input anynumber here in random seed.But you have to write a code that generate the random number in this same box

mean_vector1 = np.array([0,0,0]) #This specifies the mean vector which is the mean of all the vectors to be generated
mean_vector2 = np.array([1,1,1]) #This specifies another mean vector which is the mean of all the vectors to be generated
cov_matrix = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]) ## This is the covariance matrix,which defines the spread of data and relationship between axis.

#If i want a 4D data to be generated,then i have to specify 4D mean and 4D of covariance
first_20_random1 = np.random.multivariate_normal(mean_vector1,cov_matrix,20) # I want a 20 data with mean [0,0,0] and with given spread
first_20_random2 = np.random.multivariate_normal(mean_vector2,cov_matrix,20)

data = np.vstack([first_20_random1,first_20_random2])
df = pd.DataFrame(data)



target = np.hstack([np.zeros(20),np.ones(20)])
target = pd.DataFrame(target)
df = np.hstack([df,target])
df = pd.DataFrame(df)

df = df.rename(columns={0:'feature1',1:'feature2',2:'feature3',3:'target'})

In [144]:
df

feature1  feature2  feature3  target
0   0.257400 -0.908481 -0.378503     0.0
1  -0.534916  0.858073 -0.413010     0.0
2   0.498189  2.010199  1.262862     0.0
3  -0.439215 -0.346438  0.455320     0.0
4  -1.668663 -0.862085  0.492911     0.0
5  -0.124313  1.935136 -0.618443     0.0
6  -1.046839 -0.889618  0.014041     0.0
7  -0.160830  2.230360 -0.399116     0.0
8   0.054445  0.884182 -0.107981     0.0
9   0.555607  0.394907  0.837205     0.0
10 -1.407878  0.807849 -0.138284     0.0
11  0.187179 -0.386658  1.659049     0.0
12 -2.047069  1.399317 -0.679007     0.0
13  1.528985  1.221216  1.014989     0.0
14  0.828130  2.266293 -0.594956     0.0
15 -0.581270 -0.655894  0.925149     0.0
16 -1.299161  1.011167 -0.288440     0.0
17 -1.067713 -1.077601 -0.796774     0.0
18 -1.486043  0.514129  0.851791     0.0
19  0.958673 -0.626484  0.307931     0.0
20  1.005206  1.691532  1.444862     1.0
21  1.090280 -0.858343  0.833420     1.0
22  1.110876  0.305227  0.730824     1.0
23 -0.299225  0.678895  1.505869     1.0
24  3.089060 -0.012709  0.976026     1.0
25  0.038531  0.907434  0.776268     1.0
26  1.832892  1.974120  1.162818     1.0
27  0.885508  2.186468  1.179792     1.0
28  2.516442 -0.634032  2.781971     1.0
29  0.382272 -0.086399  0.955247     1.0
30 -0.163702  1.568939  0.537356     1.0
31  1.287355  0.022661  0.777564     1.0
32  1.096932  0.811616  2.591602     1.0
33  1.585811  1.203675 -0.856521     1.0
34  1.378189  2.236140  0.310028     1.0
35  0.801645 -2.025740 -0.245626     1.0
36 -1.084039  1.104122  0.849767     1.0
37  0.894183  0.563046  2.019136     1.0
38 -0.232803  0.925875  1.596389     1.0
39  0.820607  0.909205  0.174920     1.0

### 1) Applying standarization

In [147]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
ss = StandardScaler()

X = df.drop(['target'],axis=1)
Y = df['target']

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=3)

In [149]:
X_train.shape , X_test.shape, Y_train.shape,Y_test.shape

((32, 3), (8, 3), (32,), (8,))

In [151]:
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

### 2) Find Covariance Matrix

In [154]:
cov_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
cov_matrix

array([[ 1.32920211,  0.08443429,  0.41260965],
       [ 0.08443429,  1.20547332, -0.04256365],
       [ 0.41260965, -0.04256365,  0.80054873]])

### 3) Finding an eigen value and eigen vector

In [157]:
eigen_values ,eigen_vector = np.linalg.eig(cov_matrix)

In [159]:
eigen_values

array([0.56534603, 1.56308079, 1.20679733])

In [161]:
eigen_vector

array([[-0.48209894,  0.87293013,  0.07465662],
       [ 0.12128426,  0.15088872, -0.98108242],
       [ 0.86768125,  0.46392412,  0.17861597]])

In [163]:
pc = eigen_vector[0:2]

In [165]:
pc

array([[-0.48209894,  0.87293013,  0.07465662],
       [ 0.12128426,  0.15088872, -0.98108242]])

### Now PC is i coordinate of (2,3) which is (3,2) after transpose.And we have input feature as (1000,3).

In [168]:
input_feature = df.iloc[:,0:3]
pc = pc.T #Performing transpose

transformed_df = np.dot(input_feature,pc)
# (1000,3).(3,2)

In [170]:
transformed_df

array([[-0.9453908 ,  0.26548171],
       [ 0.97608639,  0.46979358],
       [ 1.60886827, -0.87523244],
       [-0.05667843, -0.55224953],
       [ 0.08871917, -0.81604767],
       [ 1.70299928,  0.88365619],
       [-0.27084581, -0.27497327],
       [ 1.99468732,  0.70859542],
       [ 0.73751981,  0.24595416],
       [ 0.13937126, -0.6943938 ],
       [ 1.37360887,  0.08680955],
       [-0.30390517, -1.66330408],
       [ 2.15770343,  0.62902583],
       [ 0.40468971, -0.62607785],
       [ 1.53465722,  1.02609769],
       [-0.22325185, -1.07711315],
       [ 1.48746835,  0.27798944],
       [-0.48541139,  0.48960613],
       [ 1.22880986, -0.93833439],
       [-0.98606316, -0.28036308],
       [ 1.09984909, -1.04038016],
       [-1.21267566, -0.81493418],
       [-0.21454933, -0.53621181],
       [ 0.8493067 , -1.41123513],
       [-1.42745983, -0.58482526],
       [ 0.83150412, -0.61998809],
       [ 0.92644516, -0.62064711],
       [ 1.56981096, -0.72016125],
       [-1.55894694,

In [176]:
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])

In [180]:
new_df.head()

PC1       PC2
0 -0.945391  0.265482
1  0.976086  0.469794
2  1.608868 -0.875232
3 -0.056678 -0.552250
4  0.088719 -0.816048

In [182]:
new_df['target'] = df['target']

In [184]:
new_df

PC1       PC2  target
0  -0.945391  0.265482     0.0
1   0.976086  0.469794     0.0
2   1.608868 -0.875232     0.0
3  -0.056678 -0.552250     0.0
4   0.088719 -0.816048     0.0
5   1.702999  0.883656     0.0
6  -0.270846 -0.274973     0.0
7   1.994687  0.708595     0.0
8   0.737520  0.245954     0.0
9   0.139371 -0.694394     0.0
10  1.373609  0.086810     0.0
11 -0.303905 -1.663304     0.0
12  2.157703  0.629026     0.0
13  0.404690 -0.626078     0.0
14  1.534657  1.026098     0.0
15 -0.223252 -1.077113     0.0
16  1.487468  0.277989     0.0
17 -0.485411  0.489606     0.0
18  1.228810 -0.938334     0.0
19 -0.986063 -0.280363     0.0
20  1.099849 -1.040380     1.0
21 -1.212676 -0.814934     1.0
22 -0.214549 -0.536212     1.0
23  0.849307 -1.411235     1.0
24 -1.427460 -0.584825     1.0
25  0.831504 -0.619988     1.0
26  0.926445 -0.620647     1.0
27  1.569811 -0.720161     1.0
28 -1.558947 -2.519806     1.0
29 -0.188398 -0.903849     1.0
30  1.488613 -0.310310     1.0
31 -0.542801 -0.603299     1.0
32  0.373134 -2.287071     1.0
33  0.222262  1.214272     1.0
34  1.310716  0.200398     1.0
35 -2.173139  0.032545     1.0
36  1.549876 -0.798568     1.0
37  0.211157 -1.787531     1.0
38  1.039640 -1.454721     1.0
39  0.411117  0.065104     1.0

### Here we have converted 3D feature into 2D using PCA by capturing the important feature