# COLUMN TRANSFORMER
transformation1 = ColumnTransformer(transformers = [], remainder= 'passthrough')

In [14]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv('covid_toy.csv')

In [6]:
df.sample(5)

age  gender  fever cough       city has_covid
5    84  Female    NaN  Mild  Bangalore       Yes
82   24    Male   98.0  Mild    Kolkata       Yes
86   25    Male  104.0  Mild  Bangalore       Yes
50   19    Male  101.0  Mild      Delhi       Yes
11   65  Female   98.0  Mild     Mumbai       Yes

In [8]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [40]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

<h2 style = 'color :red;'> SimpleInputer:</h2><h2>Here we will be using simpleinputer function to handle missing value.Instead of removing rows or columns with missing values (which can lead to significant data loss), imputing values allows you us retain the entire dataset for analysis and modeling by replacing value with suitable mean or other</h2>

In [12]:
X = df[['age','gender','fever','cough','city']]
Y = df[['has_covid']]

In [16]:
X_train,X_test,Y_train,Y_test = train_test_split(X,
                                                Y,
                                                test_size=0.2,
                                                random_state=0)

In [24]:
X_train.shape

(80, 5)

In [22]:
X_test.shape

(20, 5)

In [48]:
Si = SimpleImputer()
categories = [['Mild','Strong']]
Oe = OrdinalEncoder(categories=categories)
Ohe = OneHotEncoder(drop = 'first',sparse_output=False,dtype=np.int32)

In [34]:
X_train_fever = Si.fit_transform(X_train[['fever']])
X_test_fever = Si.transform(X_test[['fever']])

In [67]:
X_train_fever

array([[ 99.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [ 99.        ],
       [ 99.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [ 99.        ],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [100.91549296],
       [100.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [102.        ],
       [101.        ],
       [100.91549296],
       [100.91549296],
       [104.        ],
       [103.        ],
       [102.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [103.        ],
       [104.        ],
       [ 99

In [44]:
X_train_cough = Oe.fit_transform(X_train [['cough']])
X_test_cough = Oe.transform (X_test[['cough']])

In [50]:
X_train_gender_city = Ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city = Ohe.transform(X_test[['gender','city']])

In [54]:
X_test_gender_city

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

<h3 style = 'color :red;'>From np.concate and np.hstack,we can use any of this to join np array.But in np.concate we should specify axis = 1 to join horizontally and axis = 0 to join vertically</h3>

In [69]:
age = X_train['age'].values
# np.concatenate((age,X_train_cough,X_train_fever,X_train_gender_city),axis = 1)

In [77]:
from sklearn.preprocessing import MinMaxScaler
No = MinMaxScaler()
X_train_age = No.fit_transform(X_train[['age']])
X_test_age = No.transform(X_test[['age']])

In [81]:
X_train_age

array([[0.21518987],
       [0.64556962],
       [0.32911392],
       [0.88607595],
       [0.84810127],
       [0.7721519 ],
       [0.11392405],
       [0.06329114],
       [0.24050633],
       [0.94936709],
       [0.24050633],
       [0.11392405],
       [0.6835443 ],
       [0.62025316],
       [0.07594937],
       [0.35443038],
       [0.74683544],
       [0.83544304],
       [0.06329114],
       [0.36708861],
       [0.27848101],
       [0.96202532],
       [0.27848101],
       [0.97468354],
       [0.75949367],
       [0.82278481],
       [0.44303797],
       [0.55696203],
       [0.55696203],
       [1.        ],
       [0.41772152],
       [0.01265823],
       [0.69620253],
       [0.87341772],
       [0.13924051],
       [0.17721519],
       [0.75949367],
       [0.97468354],
       [0.94936709],
       [0.53164557],
       [0.88607595],
       [0.98734177],
       [0.58227848],
       [0.55696203],
       [0.5443038 ],
       [0.13924051],
       [0.36708861],
       [0.810

In [83]:
final_one = np.concatenate((X_train_age,X_train_cough,X_train_fever,X_train_gender_city),axis = 1)

In [85]:
final_one.shape

(80, 7)

## Now instead of doing all of these step,we can simply use COlumnTranformer to do our task

<h1 style = 'color:red;'>ColumnTransformer</h1>

In [93]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [113]:
Ct = ColumnTransformer(
    transformers=[
        ('trn1', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
        ('trn2', SimpleImputer(), ['fever']),
        ('trn3', OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32), ['city', 'gender'])
    ],
    remainder='passthrough'
)


In [115]:
X_train_transformed = Ct.fit_transform(X_train)
X_test_transformed = Ct.transform(X_test)

In [117]:
X_train_transformed

array([[  0.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  22.        ],
       [  1.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [  0.        ,  98.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  31.        ],
       [  1.        , 104.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  75.        ],
       [  0.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  72.        ],
       [  1.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  66.        ],
       [  1.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  14.        ],
       [  1.        ,  98.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  10.        ],
       [  0.        ,  98.        ,   0.        ,   1.        ,
          0.    

In [133]:
pd.DataFrame(X_train_transformed)

0      1    2    3    4    5     6
0   0.0   99.0  0.0  0.0  0.0  0.0  22.0
1   1.0  104.0  0.0  0.0  0.0  0.0  56.0
2   0.0   98.0  0.0  1.0  0.0  0.0  31.0
3   1.0  104.0  1.0  0.0  0.0  0.0  75.0
4   0.0   99.0  0.0  0.0  0.0  1.0  72.0
..  ...    ...  ...  ...  ...  ...   ...
75  1.0  101.0  0.0  1.0  0.0  0.0  51.0
76  0.0   99.0  0.0  0.0  0.0  1.0  65.0
77  0.0  104.0  0.0  0.0  1.0  1.0  42.0
78  0.0  104.0  0.0  0.0  0.0  0.0  18.0
79  1.0  102.0  1.0  0.0  0.0  1.0  20.0

[80 rows x 7 columns]

In [131]:
np.hstack((d,X_train_transformed))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)