<h2 style = 'color:purple;'><u>Note to rememeber :</u>Here gradient descent is not only applied to linear regression but also in other algorithm like logistic regression or deep learning.We have to use this formula in all b_new = b_old - n*slope,here only slope is different in all.Slope is a derivative of a loss function with respect to b in all case.So here in linear regression we differentiate slope w.r.t b and get slope as -2*np.sum(Y - m*X.ravel() - b).In other algorithm too we have to differentiate their loss function and calculate their slope.Only slope is different in formula b_new = b_old - n*m while applying gradient descent in other algorithm</h2>

In [79]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression

In [175]:
X,Y =make_regression(n_samples=20, n_features=1, n_informative=1, n_targets=1,noise=80,random_state=13)

In [177]:
X ,Y

(array([[-0.04450308],
        [-0.78898902],
        [ 0.53233789],
        [ 0.9137407 ],
        [ 0.75376638],
        [-1.04537713],
        [ 0.86121137],
        [ 0.12730328],
        [ 1.47868574],
        [ 1.3501879 ],
        [-0.24332625],
        [-1.26160595],
        [ 0.56284679],
        [ 0.31735092],
        [-0.71239066],
        [ 1.34510171],
        [-0.02677165],
        [ 2.15038297],
        [ 0.60628866],
        [ 0.45181234]]),
 array([ -94.65916603,  109.63621212,   19.04994344,  -88.88645663,
         -78.94743471, -111.19040099, -128.07635379,  -19.35784681,
         -54.31575284,  -21.00717628,  -36.27048044,   42.07716836,
          15.62116804,   11.84998644,   66.22051641,   40.79621837,
          60.87478741,  -30.52448303,  -88.66957067,  -74.45970822]))

In [179]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [181]:
lr = LinearRegression()
lr.fit(X_train,Y_train)
Y_pred = lr.predict(X_test)


In [183]:
from sklearn.metrics import r2_score
r2_score(Y_test,Y_pred)
# Y_pred.shape,Y_test.shape

-0.2943540700748284

In [185]:
lr.coef_ ### value of slope i.e. m

array([-28.08207829])

In [187]:
lr.intercept_  ### Value of b

-22.153433743184706

In [198]:
import numpy as np
class MeroRegression:
    def __init__(self,learning_rate,epoch):
        self.learning_rate = learning_rate
        self.epoch = epoch
        self.m = 100          #Taking a random value for m
        self.b = -120         #Taking a random value for b 
    def fit(self,X,Y):
        for i in range(self.epoch):
            loss_slope_b = -2 * np.sum(Y - self.m * X.ravel() - self.b)
            loss_slope_m = -2 * np.sum((Y - self.m * X.ravel() - self.b)*X.ravel())
            self.b = self.b - (self.learning_rate * loss_slope_b)
            self.m = self.m - (self.learning_rate * loss_slope_m)
            print('Iteration : ',i)
            print(self.m)
            print(self.b)
        print(self.m)
        print(self.b)
    def predict(self,X):
        return self.m*X.ravel() + self.b

In [200]:
gd = MeroRegression(0.01,100)
gd.fit(X_train,Y_train)

Iteration :  0
81.73441416062579
-100.64187288023683
Iteration :  1
65.56931177197029
-85.77377993002428
Iteration :  2
51.47441501187082
-74.15492986505409
Iteration :  3
39.31013034198281
-64.9387590491009
Iteration :  4
28.887720929781153
-57.53657717210729
Iteration :  5
20.003883444865167
-51.53046167430363
Iteration :  6
12.459800084089121
-46.61725270295901
Iteration :  7
6.070888911957818
-42.57224764094431
Iteration :  8
0.6710805336569123
-39.22542329968502
Iteration :  9
-3.886038985550403
-36.44566611465625
Iteration :  10
-7.727801328470102
-34.1301553369365
Iteration :  11
-10.963897298324927
-32.19709011098835
Iteration :  12
-13.688188599558211
-30.580609376942775
Iteration :  13
-15.980606159728787
-29.22716832658185
Iteration :  14
-17.908980554016537
-28.092897239717374
Iteration :  15
-19.530727378660504
-27.141634675504964
Iteration :  16
-20.89435566812407
-26.34343276145494
Iteration :  17
-22.040793150192002
-25.673400022649897
Iteration :  18
-23.00453601769056

### Within 100 iteration,our b and M at first maintains within their starting value i.e. -120 and 100 and after iteration 42 it maintains a constant value i.e. b as -22 and m as -28 which is very close to its original value as predicted by linear regression

In [203]:
y_pred = gd.predict(X_test)

In [205]:
from sklearn.metrics import r2_score
r2_score(Y_test,y_pred)

-0.2943540520485939

### Here r2_score is also quite similar as of calculated by LinearRegression

### If r2_score comes negative then it signifies that our model is poorely predicting the data

# Here when starting with a random value of b and m,our line is at random position in term of both angle(m) and height(b).So on each epoch when we adjust b and m using gradient descent,then our line gets fit into its most optimal position interm of both height and angle

<img src = 'animation4.gif'/>

# Here on second picture,on first epoch our cost function is high and as epoch increases,our cost function gradually goes on decreasing and maintains a most minimum cost function after cetain epoch

<img src='animation3.gif' />